### PR TITLE
Port old unit tests to the Catch unit test framework

### PR DESCRIPTION
**Pull request by Manuzor**
Guess it can't hurt to test it on another system before merging.

### CODE REVIEW

**Comment by Manuzor** [comment]
By the way, this is already done and works on my system. It was actually pretty straight forward except for some minor hidden automatic stuff that the old ezEngine test framework did (namely update/shutdown the engine automatically after each test).

**Comment by pampersrocker** [comment]
I get the followin error if I try to configure CMake: 
```
CMake Error at tests/CMakeLists.txt:2 (add_subdirectory):
  add_subdirectory given source "krEngineTests_old" which is not an existing
  directory.
```

**Comment by Manuzor** [comment]
Did you try the latest change? Because the current version of `tests/CMakeLists.txt` has exactly one line: `add_subdirectory("krEngineTests")`

**Comment by Manuzor** [comment]
How about now? ^^

**Comment by pampersrocker** [comment]
:+1:

**Pull request merged**
